### ISSUE TITLE
Issue Encountered While Creating Complex Automation

### ISSUE THREAD

**Issue by dadaloop82** [jekalmin/extended_openai_conversation#171]
Firstly, I would like to express my appreciation for your project. 
I have been searching for it for a long time and I am truly delighted to have found it.

However, I encountered an issue when attempting to create a complex automation. 
Specifically, I aimed to create an automation as follows:

"When any sensor for odors, substances, or pollutants provided by the Dyson purifier exceeds the normal threshold, then turn on the Dyson purifier and set it to an appropriate speed. The speed should increase as the level of substances increases and decrease as it decreases. If the level of substances, odors, or agents is below normal, then turn off the purifier."

Unfortunately, when attempting to implement this automation, I encountered the following error ...

Please let me know if you require any further information or clarification.
Thank you for your attention to this matter.

> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 992, in recognize_intent
>     conversation_result = await conversation.async_converse(
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 543, in async_converse
>     result = await agent.async_process(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
>     query_response = await self.query(user_input, messages, exposed_entities, 0)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 380, in query
>     return await self.execute_function_call(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 406, in execute_function_call
>     return await self.execute_function(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 432, in execute_function
>     result = await function_executor.execute(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/helpers.py", line 211, in execute
>     return await self.add_automation(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/helpers.py", line 292, in add_automation
>     automation_config = yaml.safe_load(arguments["automation_config"])
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
>     return load(stream, SafeLoader)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
>     return loader.get_single_data()
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/constructor.py", line 49, in get_single_data
>     node = self.get_single_node()
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 36, in get_single_node
>     document = self.compose_document()
>                ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 55, in compose_document
>     node = self.compose_node(None, None)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 82, in compose_node
>     node = self.compose_sequence_node(anchor)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 111, in compose_sequence_node
>     node.value.append(self.compose_node(node, index))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
>     node = self.compose_mapping_node(anchor)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 133, in compose_mapping_node
>     item_value = self.compose_node(node, item_key)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 82, in compose_node
>     node = self.compose_sequence_node(anchor)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 111, in compose_sequence_node
>     node.value.append(self.compose_node(node, index))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
>     node = self.compose_mapping_node(anchor)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 133, in compose_mapping_node
>     item_value = self.compose_node(node, item_key)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 84, in compose_node
>     node = self.compose_mapping_node(anchor)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/composer.py", line 127, in compose_mapping_node
>     while not self.check_event(MappingEndEvent):
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/parser.py", line 98, in check_event
>     self.current_event = self.state()
>                          ^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
>     raise ParserError("while parsing a block mapping", self.marks[-1],
> yaml.parser.ParserError: while parsing a block mapping
>   in "<unicode string>", line 12, column 9:
>             speed: '{{ state_attr(''sensor.p ... 
>             ^
> expected <block end>, but found '<scalar>'
>   in "<unicode string>", line 12, column 105:
>      ... nic_compounds_index'', ''value' ) * 10 }}

**Comment by jekalmin** [comment]
It seems a yaml created by LLM is not valid.
Add [logging](https://github.com/jekalmin/extended_openai_conversation#logging) and see how yaml looks.

I also had two versions of [function](https://github.com/jekalmin/extended_openai_conversation#3-1-add-automation), one for English and one for Korean because LLM didn't create valid yaml depending on how questions is asked.
