### ISSUE TITLE
Local LLM Functionary-7b-v2.1-GGUF and Extended OpenAI Conversation

### ISSUE THREAD

**Issue by FutureProofHomes** [jekalmin/extended_openai_conversation#174]
@jekalmin I am running [Functionary-7b-v2.1-GGUF](https://huggingface.co/meetkai/functionary-7b-v2.1-GGUF) model via [Python Bindings for llama.cpp](https://llama-cpp-python.readthedocs.io/en/latest).  Here is an example of my python script successfully calling the LLM and returning the correct response for `get_current_weather`:

![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/b868833f-5645-43de-ba8b-238bb7087e97)

Hwoever, when I issue the same request from Home Assistant via Extended OpenAI Conversation I get the following error:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/de609fbe-0710-48ee-b211-7d8478c07c8d)

Here are the Home Assistant Logs:
```
2024-03-16 01:27:32.831 INFO (MainThread) [custom_components.extended_openai_conversation] Prompt for /data/models/huggingface/models--meetkai--functionary-7b-v2.1-GGUF/snapshots/4386d5a19700bd0ae1582574e3de13a218fb1c8e/functionary-7b-v2.1.q4_0.gguf: [{'role': 'system', 'content': "I want you to act as smart home manager of Home Assistant.\nI will provide information of smart home along with a question, you will truthfully make correction or answer using information provided in one sentence in everyday language.\n\nCurrent Time: 2024-03-16 01:27:32.826442-04:00\n\nAvailable Devices:\n```csv\nentity_id,name,state,aliases\nweather.clusterhome,Local Weather,partlycloudy,\n```\n\nThe current state of devices is provided in available devices.\nUse execute_services function only for requested action, not for current states.\nDo not execute service without user's confirmation.\nDo not restate or appreciate what user says, rather make a quick inquiry."}, {'role': 'user', 'content': 'What is the weather in New York?’}]
```

```
2024-03-16 01:27:37.786 INFO (MainThread) [custom_components.extended_openai_conversation] Response {'id': 'chatcmpl-05d7ce5d-c3d2-4fd1-ac71-1af5266ea5d4', 'choices': [{'finish_reason': 'tool_calls', 'index': 0, 'message': {'role': 'assistant', 'function_call': {'arguments': '{}', 'name': ' get_current_weather'}, 'tool_calls': [{'id': 'call_zrdjmFbhRmjp7l9010Jvr4EP', 'function': {'arguments': '{}', 'name': ' get_current_weather'}, 'type': 'function'}]}}], 'created': 1710566857, 'model': '/data/models/huggingface/models--meetkai--functionary-7b-v2.1-GGUF/snapshots/4386d5a19700bd0ae1582574e3de13a218fb1c8e/functionary-7b-v2.1.q4_0.gguf', 'object': 'chat.completion', 'usage': {'completion_tokens': 2, 'prompt_tokens': 349, 'total_tokens': 351}}
```

```
2024-03-16 01:27:37.790 ERROR (MainThread) [custom_components.extended_openai_conversation] function ' get_current_weather' does not exist
Traceback (most recent call last):
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
    query_response = await self.query(user_input, messages, exposed_entities, 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 384, in query
    return await self.execute_tool_calls(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 477, in execute_tool_calls
    raise FunctionNotFound(function_name)
custom_components.extended_openai_conversation.exceptions.FunctionNotFound: function ' get_current_weather' does not exist
```
If you inspect those logs closely you'll see that it looks like Extended OpenAI Conversation is not passing my spec for `get_current_weather`.  What am I doing wrong here?  Any tips?

Here are the options I'm passing into your plug-in.  Notice that I am defining the ' get_current_weather' spec:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/89192a0b-1115-457e-b3ff-b5cfa49da41a)

**Comment by rfam13** [comment]
https://huggingface.co/TheBloke/NexusRaven-V2-13B-GGUF

this is the only one I have had any luck calling functions, specifically the execute_services.  This does work if you instruct it what to do in the prompt.  I am having success even with Q2.

**Comment by jekalmin** [comment]
@FutureProofHomes 

Thanks for reporting an issue.
It seems LLM tries to call ` get_current_weather` function while your function name is `get_current_weather`.

In order to match ` get_current_weather` and `get_current_weather`, you should change the [code](https://github.com/jekalmin/extended_openai_conversation/blob/1.0.4-beta2/custom_components/extended_openai_conversation/__init__.py#L455) like below.

```python
function_name = tool.function.name.strip()
```

and [here](https://github.com/jekalmin/extended_openai_conversation/blob/1.0.4-beta2/custom_components/extended_openai_conversation/__init__.py#L400) like below.

```python
function_name = message.function_call.name.strip()
```

Ideally, LLM doesn't contain extra space in function names, but it happens.
Since it's a workaround rather than solution, I didn't apply this to the code yet.

**Comment by FutureProofHomes** [comment]
Thank you @jekalmin.  I actually found this solution a few days ago and should have closed the ticket.

Perhaps we could consider merging this change with main because it wouldn't harm strings that have a trailing whitespace. e.g. the workaround doesn't have a negative impact that breaks and existing code, right?

**Comment by jekalmin** [comment]
@FutureProofHomes 

Yes, it should not break any existing code.
Although it is not ideal, as you suggested, it would help digging Local LLM.

I would probably merge this in the next release.

**Comment by FutureProofHomes** [comment]
I got everything working by sacrificing history capability.  The pydantic schema behind the Functionary model isn't exactly the same as the OpenAI payloads I guess.  These are the changes I made to `__init.py__`.

Commented out `self.history`:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/6a15b4be-2b83-4dcc-bc48-e671833afe0f)


Commented out `self.history` again and removed `exclude_none=True` param from `model_dump()`:
![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/7ec96a12-ca0d-4807-8ce1-feacdc4d5693)

Stripped whitespaces and again removed `exclude_none=True` param from `model_dump()  and had to not append tool calls to message.
![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/73943b48-b7cc-44b7-9baf-543cbe3bb9f7)

@jekalmin would you like me to create a `Functionary` branch on the repo?

**Comment by FutureProofHomes** [comment]
@jekalmin it would be really awesome if you could get this up and running on your local machine, then help figure out how to get history working.  You could then claim your extension works with a fully local LLM.  It can control lights, locks, run scripts, and report the status of the home.  If we fine-tune this model with more HA data it could be as powerful as OpenAI.

**Comment by FutureProofHomes** [comment]
My current context threshold is set to 13000 with this model.  Should be plenty enough to handle normal conversation history, I think.  Here's an example of how it behaves currently without history.  In this case it doesn't know what I mean when I say, turn "them on".

![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/4fc8e59b-0ac4-495e-9b1b-8886710d1fe2)

**Comment by FutureProofHomes** [comment]
In case anyone is interested: 
![image](https://github.com/jekalmin/extended_openai_conversation/assets/155350996/1b061909-28b6-4f03-b356-c844d97a1ebe)

**Comment by FutureProofHomes** [comment]
Good catch.  Will set my Extended OpenAI Conversation config to 8k.  Thanks.

**Comment by FutureProofHomes** [comment]
FYI - I believe[ this is our root cause](https://github.com/abetlen/llama-cpp-python/issues/1314) for the issue.  I'm fine if we think we should close this issue.

**Comment by jekalmin** [comment]
Thanks @FutureProofHomes for work done!
Please give me time to catch up where you are.

**Comment by Anto79-ops** [comment]
hello, I wanted to mention im also interested in this. I'm using LocalAI and this model works most of the time using it as is, with this integration:

https://huggingface.co/macadeliccc/laser-dolphin-mixtral-2x7b-dpo

I'm trying to get the new Llama-3-instruct 70b to work with this intergration. It does not seem to work well, becuse I think the function calling syntax is a bit different. Anyone know how to modify this model.yaml to work with this integrations functions?

```
name: llama3-8b-instruct
mmap: true
parameters:
  model: huggingface://second-state/Llama-3-8B-Instruct-GGUF/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf

template:
  chat_message: |
    <|start_header_id|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "tool"}}tool{{else if eq .RoleName "user"}}user{{end}}<|end_header_id|>

    {{ if .FunctionCall -}}
    Function call:
    {{ else if eq .RoleName "tool" -}}
    Function response:
    {{ end -}}
    {{ if .Content -}}
    {{.Content -}}
    {{ else if .FunctionCall -}}
    {{ toJson .FunctionCall -}}
    {{ end -}}
    <|eot_id|>
  function: |
    <|start_header_id|>system<|end_header_id|>

    You are a function calling AI model. You are provided with function signatures within <tools></tools> XML tags. You may call one or more functions to assist with the user query. Don't make assumptions about what values to plug into functions. Here are the available tools:
    <tools>
    {{range .Functions}}
    {'type': 'function', 'function': {'name': '{{.Name}}', 'description': '{{.Description}}', 'parameters': {{toJson .Parameters}} }}
    {{end}}
    </tools>
    Use the following pydantic model json schema for each tool call you will make:
    {'title': 'FunctionCall', 'type': 'object', 'properties': {'arguments': {'title': 'Arguments', 'type': 'object'}, 'name': {'title': 'Name', 'type': 'string'}}, 'required': ['arguments', 'name']}<|eot_id|><|start_header_id|>assistant<|end_header_id|>
    Function call:
  chat: |
    <|begin_of_text|>{{.Input }}
    <|start_header_id|>assistant<|end_header_id|>
  completion: |
    {{.Input}}
context_size: 8192
f16: true
stopwords:
- <|im_end|>
- <dummy32000>
- "<|eot_id|>"
usage: |
      curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
          "model": "llama3-8b-instruct",
          "messages": [{"role": "user", "content": "How are you doing?", "temperature": 0.1}]
      }'
 ```
