### ISSUE TITLE
Google Search not working?

### ISSUE THREAD

**Issue by alexkahler** [jekalmin/extended_openai_conversation#180]
I tried setting up the Google Search function call, but it's returning an error. Something about the JSON package from Google Search not parsing well, if I'm guessing right? I would love some more feedback on this.

```
2024-03-25` 02:04:42.870 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140409109869248] Error handling message: Unknown error (unknown_error) REDACTED from 192.168.50.250 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
script_result = await script_obj.async_run(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1600, in async_run
return await asyncio.shield(run.async_run())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 435, in async_run
await self._async_step(log_exceptions=False)
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 487, in _async_step
self._handle_exception(
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 512, in _handle_exception
raise exception
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 485, in _async_step
await getattr(self, handler)()
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 723, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 685, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2319, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2356, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 178, in handle_process
result = await async_converse(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 543, in async_converse
result = await agent.async_process(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
query_response = await self.query(user_input, messages, exposed_entities, 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 380, in query
return await self.execute_function_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 406, in execute_function_call
return await self.execute_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 432, in execute_function
result = await function_executor.execute(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/helpers.py", line 496, in execute
value = value_template.async_render_with_possible_json_value(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 753, in async_render_with_possible_json_value
render_result = _render_with_context(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 2364, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
TypeError: 'builtin_function_or_method' object is not iterable
```

I'm using the standard Google Search example (with my own CX and API KEY).
```
- spec:
    name: search_google
    description: Search Google using the Custom Search API.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The search query.
      required:
      - query
  function:
    type: rest
    resource_template: "https://www.googleapis.com/customsearch/v1?key=[GOOGLE_API_KEY]&cx=[GOOGLE_PROGRAMMING_SEARCH_ENGINE]:omuauf_lfve&q={{ query }}&num=3"
    value_template: >-
      {% if value_json.items %}
      ```csv
      title,link
      {% for item in value_json.items %}
      "{{ item.title | replace(',', ' ') }}","{{ item.link }}"
      {% endfor %}
      ```
      {% else %}
      No results found,
      {% endif %}
```

**Comment by Al3XKOoL** [comment]
I want this feature.

**Comment by jekalmin** [comment]
Can you try this?

```yaml
- spec:
    name: search_google
    description: Search Google using the Custom Search API.
    parameters:
      type: object
      properties:
        query:
          type: string
          description: The search query.
      required:
      - query
  function:
    type: rest
    resource_template: "https://www.googleapis.com/customsearch/v1?key=[GOOGLE_API_KEY]&cx=[GOOGLE_PROGRAMMING_SEARCH_ENGINE]&q={{ query }}&num=3"
    value_template: >-
      {% if value_json["items"] %}
      ```csv
      title,link
      {% for item in value_json["items"] %}
      "{{ item.title | replace(',', ' ') }}","{{ item.link }}"
      {% endfor %}
      ```
      {% else %}
      No results found,
      {% endif %}
```

**Comment by alexkahler** [comment]
Tried calling both function from Developer Tools > Services 

```
service: conversation.process
data:
  agent_id: 075e43b1a0ff379c69f9ef17385afd9b
  text: Hi chat, what are the latest news headlines?
response_variable: chatgpt

```
Received error message:
`Failed to call service conversation.process. Unknown error`

System logs:
```
2024-03-26 16:45:05.735 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140409278469568] Error handling message: Unknown error (unknown_error) REDACTED from 192.168.50.250 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
script_result = await script_obj.async_run(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1600, in async_run
return await asyncio.shield(run.async_run())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 435, in async_run
await self._async_step(log_exceptions=False)
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 487, in _async_step
self._handle_exception(
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 512, in _handle_exception
raise exception
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 485, in _async_step
await getattr(self, handler)()
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 723, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 685, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2319, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2356, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 178, in handle_process
result = await async_converse(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 543, in async_converse
result = await agent.async_process(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
query_response = await self.query(user_input, messages, exposed_entities, 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 380, in query
return await self.execute_function_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 406, in execute_function_call
return await self.execute_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 432, in execute_function
result = await function_executor.execute(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/helpers.py", line 496, in execute
value = value_template.async_render_with_possible_json_value(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 753, in async_render_with_possible_json_value
render_result = _render_with_context(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 2364, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
TypeError: 'builtin_function_or_method' object is not iterable
```
Neither worked - and produced the same error logs.

I thought that it might be my API key messing up or something, so I tried inputting the URL `https://www.googleapis.com/customsearch/v1?key=A*REDACTED API KEY*&cx=8*REDACTED GOOGLE PROGRAMMING ENGINE*&q=news&num=3` into my browser, which worked without problems:
```
{
    "kind": "customsearch#search",
    "url": {
        "type": "application/json",
        "template": "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json"
    },
    "queries": {
        "request": [
            {
                "title": "Google Custom Search - news",
                "totalResults": "30560000000",
                "searchTerms": "news",
                "count": 3,
                "startIndex": 1,
                "inputEncoding": "utf8",
                "outputEncoding": "utf8",
                "safe": "off",
                "cx": "8709c6cdabe0b452a"
            }
        ],
        "nextPage": [
            {
                "title": "Google Custom Search - news",
                "totalResults": "30560000000",
                "searchTerms": "news",
                "count": 3,
                "startIndex": 4,
                "inputEncoding": "utf8",
                "outputEncoding": "utf8",
                "safe": "off",
                "cx": "8709c6cdabe0b452a"
            }
        ]
    },
    "context": {
        "title": " Home Assistant"
    },
    "searchInformation": {
        "searchTime": 0.388444,
        "formattedSearchTime": "0.39",
        "totalResults": "30560000000",
        "formattedTotalResults": "30,560,000,000"
    },
    "items": [
        {
            "kind": "customsearch#result",
            "title": "Google News",
            "htmlTitle": "Google <b>News</b>",
            "link": "https://news.google.com/",
            "displayLink": "news.google.com",
            "snippet": "Comprehensive up-to-date news coverage, aggregated from sources all over the world by Google News.",
            "htmlSnippet": "Comprehensive up-to-date <b>news</b> coverage, aggregated from sources all over the world by Google <b>News</b>.",
            "formattedUrl": "https://news.google.com/",
            "htmlFormattedUrl": "https://<b>news</b>.google.com/",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9Zc_7F41n1Z-xtqDpv1XgQnQOO6zFB5kLatFaBuVbH92-LKaBhQhmqp8&s",
                        "width": "225",
                        "height": "225"
                    }
                ],
                "metatags": [
                    {
                        "apple-itunes-app": "app-id=459182288",
                        "og:image": "https://lh3.googleusercontent.com/J6_coFbogxhRI9iM864NL_liGXvsQp2AupsKei7z0cNNfDvGUmWUy20nuUhkREQyrpY4bEeIBuc=s0-w300-rw",
                        "theme-color": "white",
                        "og:image:width": "300",
                        "twitter:card": "summary",
                        "og:site_name": "Google News",
                        "apple-mobile-web-app-title": "News",
                        "og:image:type": "image/jpeg",
                        "title": "Google News",
                        "og:description": "Comprehensive up-to-date news coverage, aggregated from sources all over the world by Google News.",
                        "twitter:image": "https://lh3.googleusercontent.com/J6_coFbogxhRI9iM864NL_liGXvsQp2AupsKei7z0cNNfDvGUmWUy20nuUhkREQyrpY4bEeIBuc=s0-w300-rw",
                        "msapplication-tap-highlight": "no",
                        "application-name": "News",
                        "twitter:title": "Google News",
                        "og:type": "website",
                        "og:title": "Google News",
                        "og:image:height": "300",
                        "referrer": "origin",
                        "apple-mobile-web-app-status-bar-style": "black",
                        "viewport": "width=device-width,initial-scale=1,minimal-ui",
                        "apple-mobile-web-app-capable": "yes",
                        "twitter:description": "Comprehensive up-to-date news coverage, aggregated from sources all over the world by Google News.",
                        "mobile-web-app-capable": "yes",
                        "og:locale": "en_US",
                        "og:url": "https://news.google.com"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://lh3.googleusercontent.com/J6_coFbogxhRI9iM864NL_liGXvsQp2AupsKei7z0cNNfDvGUmWUy20nuUhkREQyrpY4bEeIBuc=s0-w300-rw"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "NBC News - Breaking News & Top Stories - Latest World, US ...",
            "htmlTitle": "NBC <b>News</b> - Breaking <b>News</b> &amp; Top Stories - Latest World, US ...",
            "link": "https://www.nbcnews.com/",
            "displayLink": "www.nbcnews.com",
            "snippet": "Nightly News · Famed waiters' run returns to Paris · TODAY · Family, friends, public send outpouring of support to Kate Middleton · TODAY · Excitement grows ...",
            "htmlSnippet": "Nightly <b>News</b> &middot; Famed waiters&#39; run returns to Paris &middot; TODAY &middot; Family, friends, public send outpouring of support to Kate Middleton &middot; TODAY &middot; Excitement grows&nbsp;...",
            "formattedUrl": "https://www.nbcnews.com/",
            "htmlFormattedUrl": "https://www.nbc<b>news</b>.com/",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUkz0u0hM5zPD8em_lxgycI-N26_3ycwMUMeBvrophVdPrhJX3C5A7pW2Z&s",
                        "width": "275",
                        "height": "183"
                    }
                ],
                "thumbnail": [
                    {
                        "src": "https://media4.s-nbcnews.com/j/newscms/2019_01/2705191/nbc-social-default_b6fa4fef0d31ca7e8bc7ff6d117ca9f4.social_share_1024x768_scale.png"
                    }
                ],
                "metatags": [
                    {
                        "msapplication-config": "https://nodeassets.nbcnews.com/cdnassets/projects/ramen/favicon/nbcnews/all-other-sizes-PNG.ico/browserconfig.xml",
                        "og:image": "https://media4.s-nbcnews.com/j/newscms/2019_01/2705191/nbc-social-default_b6fa4fef0d31ca7e8bc7ff6d117ca9f4.nbcnews-fp-1200-630.png",
                        "thumbnail": "https://media4.s-nbcnews.com/j/newscms/2019_01/2705191/nbc-social-default_b6fa4fef0d31ca7e8bc7ff6d117ca9f4.social_share_1024x768_scale.png",
                        "og:image:width": "1200",
                        "og:type": "website",
                        "twitter:title": "NBC News - Breaking News & Top Stories - Latest World, US & Local News",
                        "twitter:card": "summary_large_image",
                        "og:site_name": "NBC News",
                        "og:title": "NBC News - Breaking News & Top Stories - Latest World, US & Local News",
                        "og:image:height": "630",
                        "fb:pages": "155869377766434",
                        "twitter:creator": "NBCNews",
                        "og:description": "Go to NBCNews.com for breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.",
                        "twitter:image": "https://media4.s-nbcnews.com/j/newscms/2019_01/2705191/nbc-social-default_b6fa4fef0d31ca7e8bc7ff6d117ca9f4.nbcnews-fp-1024-512.png",
                        "pocket-site-verification": "7d430daabab89c549b078097430be5",
                        "twitter:image:src": "https://media4.s-nbcnews.com/j/newscms/2019_01/2705191/nbc-social-default_b6fa4fef0d31ca7e8bc7ff6d117ca9f4.nbcnews-fp-1024-512.png",
                        "branch:deeplink:unibrow": "Immigration",
                        "next-head-count": "80",
                        "fb:app_id": "10150138890205613",
                        "twitter:site": "NBCNews",
                        "viewport": "width=device-width, initial-scale=1, user-scalable=yes",
                        "twitter:description": "Go to NBCNews.com for breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.",
                        "og:locale": "en_US",
                        "og:url": "https://www.nbcnews.com"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://media-cldnry.s-nbcnews.com/image/upload/t_focal-762x508,f_auto,q_auto:best/rockcms/2024-03/240325-lifewise-al-1100-4a6b85.gif"
                    }
                ]
            }
        },
        {
            "kind": "customsearch#result",
            "title": "ABC News - Breaking News, Latest News and Videos",
            "htmlTitle": "ABC <b>News</b> - Breaking <b>News</b>, Latest <b>News</b> and Videos",
            "link": "https://abcnews.go.com/",
            "displayLink": "abcnews.go.com",
            "snippet": "Firm to turn over $1.5M for child labor violations · NYC to send 800 more cops to police subway beating · Dairy cattle test positive for bird flu · New York ...",
            "htmlSnippet": "Firm to turn over $1.5M for child labor violations &middot; NYC to send 800 more cops to police subway beating &middot; Dairy cattle test positive for bird flu &middot; New York&nbsp;...",
            "cacheId": "o1_RZUwyy1IJ",
            "formattedUrl": "https://abcnews.go.com/",
            "htmlFormattedUrl": "https://abc<b>news</b>.go.com/",
            "pagemap": {
                "cse_thumbnail": [
                    {
                        "src": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5csR8_xmsRNoDC8jfS6vK0S6KNDnsH2iR69BakiTbcAEHqeGOmwlACqSt&s",
                        "width": "300",
                        "height": "168"
                    }
                ],
                "metatags": [
                    {
                        "og:image": "https://s.abcnews.com/images/US/abc_news_default_2000x2000_update_16x9_992.jpg",
                        "twitter:app:url:iphone": "abcnewsiphone://link/section,HomePage",
                        "twitter:app:id:googleplay": "com.abc.abcnews",
                        "copyright": "2024 ABC News",
                        "og:type": "website",
                        "og:site_name": "ABC News",
                        "author": "ABC News",
                        "og:title": "ABC News – Breaking News, Latest News and Videos",
                        "twitter:app:url:ipad": "abcnewsipad://link/section,HomePage",
                        "twitter:app:id:ipad": "306934135",
                        "twitter:app:name:googleplay": "ABC News",
                        "twitter:app:id:iphone": "300255638",
                        "og:description": "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com",
                        "fb:pages": "86680728811",
                        "fb:app_id": "4942312939",
                        "twitter:app:url:googleplay": "https://abcnews.go.com/",
                        "twitter:app:name:ipad": "ABC News",
                        "viewport": "initial-scale=1.0, user-scalable=yes",
                        "og:locale": "en_US",
                        "fb:admins": "704409894",
                        "og:url": "https://abcnews.go.com",
                        "fb_title": "ABC News – Breaking News, Latest News and Videos",
                        "twitter:app:name:iphone": "ABC News"
                    }
                ],
                "cse_image": [
                    {
                        "src": "https://s.abcnews.com/images/US/abc_news_default_2000x2000_update_16x9_992.jpg"
                    }
                ]
            }
        }
    ]
}
```

**Comment by alexkahler** [comment]
The second function worked 👍 

OLD COMMENT:
Tried calling the first function from Developer Tools > Services 

```
service: conversation.process
data:
  agent_id: 075e43b1a0ff379c69f9ef17385afd9b
  text: Hi chat, what are the latest news headlines?
response_variable: chatgpt

```
Received error message:
`Failed to call service conversation.process. Unknown error`

System logs:
```
2024-03-26 16:45:05.735 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140409278469568] Error handling message: Unknown error (unknown_error) REDACTED from 192.168.50.250 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
script_result = await script_obj.async_run(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1600, in async_run
return await asyncio.shield(run.async_run())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 435, in async_run
await self._async_step(log_exceptions=False)
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 487, in _async_step
self._handle_exception(
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 512, in _handle_exception
raise exception
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 485, in _async_step
await getattr(self, handler)()
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 723, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 685, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2319, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2356, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 178, in handle_process
result = await async_converse(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 543, in async_converse
result = await agent.async_process(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
query_response = await self.query(user_input, messages, exposed_entities, 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 380, in query
return await self.execute_function_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 406, in execute_function_call
return await self.execute_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 432, in execute_function
result = await function_executor.execute(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/helpers.py", line 496, in execute
value = value_template.async_render_with_possible_json_value(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 753, in async_render_with_possible_json_value
render_result = _render_with_context(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 2364, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
TypeError: 'builtin_function_or_method' object is not iterable
```

**Comment by alexkahler** [comment]
The second function worked 👍 

OLD COMMENT:
Tried calling the first function from Developer Tools > Services 

```
service: conversation.process
data:
  agent_id: 075e43b1a0ff379c69f9ef17385afd9b
  text: Hi chat, what are the latest news headlines?
response_variable: chatgpt

```
Received error message:
`Failed to call service conversation.process. Unknown error`

System logs:
```
2024-03-26 16:45:05.735 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140409278469568] Error handling message: Unknown error (unknown_error) REDACTED from 192.168.50.250 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
script_result = await script_obj.async_run(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1600, in async_run
return await asyncio.shield(run.async_run())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 435, in async_run
await self._async_step(log_exceptions=False)
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 487, in _async_step
self._handle_exception(
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 512, in _handle_exception
raise exception
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 485, in _async_step
await getattr(self, handler)()
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 723, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 685, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2319, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2356, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 178, in handle_process
result = await async_converse(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/components/conversation/__init__.py", line 543, in async_converse
result = await agent.async_process(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
query_response = await self.query(user_input, messages, exposed_entities, 0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 380, in query
return await self.execute_function_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 406, in execute_function_call
return await self.execute_function(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/__init__.py", line 432, in execute_function
result = await function_executor.execute(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/extended_openai_conversation/helpers.py", line 496, in execute
value = value_template.async_render_with_possible_json_value(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 753, in async_render_with_possible_json_value
render_result = _render_with_context(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/template.py", line 2364, in _render_with_context
return template.render(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
TypeError: 'builtin_function_or_method' object is not iterable
```
