### ISSUE TITLE
extended_openai_conversation causing Home Assistant to freeze requiring power cycle

### ISSUE THREAD

**Issue by mmillner99** [jekalmin/extended_openai_conversation#242]
```
2024-07-09 06:39:56.522 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/etc/os-release',) inside the event loop by custom integration 'extended_openai_conversation' at custom_components/extended_openai_conversation/helpers.py, line 150: await client.models.list(timeout=10) (offender: /usr/local/lib/python3.12/site-packages/distro/distro.py, line 1099: with open(self.os_release_file, encoding="utf-8") as release_file:), please create a bug report at https://github.com/jekalmin/extended_openai_conversation/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 451, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 100, in async_setup_entry
    await validate_authentication(
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 150, in validate_authentication
    await client.models.list(timeout=10)
```

**Comment by Chaoscontrol** [comment]
Same error here. I don't think it causes a power cycle though.

**Comment by jekalmin** [comment]
Could you try once again with [1.0.5-beta2](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.5-beta2) version?
I just fixed in [PR](https://github.com/jekalmin/extended_openai_conversation/pull/286) and see if it's fixed.

**Comment by mmillner99** [comment]
sorry, i ended up rebuilding HA awhile back so I won't be able to test this

**Comment by jekalmin** [comment]
It's totally fine.
Let me close the issue first, and please let me know anyone if the problem still exists.
