### ISSUE TITLE
arguments not deserialized?

### ISSUE THREAD

**Issue by kirel** [jekalmin/extended_openai_conversation#249]
I tried setting up with llama3.1 and ollama's new openai compatible tool use API but I get

```
2024-08-02 01:01:33.177 INFO (MainThread) [custom_components.extended_openai_conversation] Response {'id': 'chatcmpl-410', 'choices': [{'finish_reason': 'tool_calls', 'index': 0, 'message': {'content': '', 'role': 'assistant', 'tool_calls': [{'id': 'call_1a28bpmj', 'function': {'arguments': '{"list":"[{\\"service\\": \\"light.turn_off\\", \\"entity_id\\": \\"light.kuche_licht\\"}]"}', 'name': 'execute_services'}, 'type': 'function'}]}}], 'created': 1722553294, 'model': 'llama3.1:8b-8k', 'object': 'chat.completion', 'system_fingerprint': 'fp_ollama', 'usage': {'completion_tokens': 37, 'prompt_tokens': 2676, 'total_tokens': 2713}}
2024-08-02 01:01:33.206 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 995, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 196, in async_process
    query_response = await self.query(user_input, messages, exposed_entities, 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 384, in query
    return await self.execute_tool_calls(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 461, in execute_tool_calls
    result = await self.execute_tool_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 494, in execute_tool_function
    result = await function_executor.execute(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 203, in execute
    return await self.execute_service(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 278, in execute_service
    await self.execute_service_single(
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 237, in execute_service_single
    domain = service_argument["domain"]
             ~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

It looks like the addon is not deserializing the string passed in the `"arguments"` field of the response and instead tries to take it as a dict.

I posted a bug in https://github.com/ollama/ollama/issues/6155 but they made me aware that a string response is actually expected because that's in the openai spec.

**Comment by kirel** [comment]
So weird: https://github.com/jekalmin/extended_openai_conversation/blob/main/custom_components/extended_openai_conversation/__init__.py#L490 clearly deserializes JSON.

Now I see it. It's double serialized - it is a ollama bug after all.
