### ISSUE TITLE
Open WebUI: Unexpected error during intent recognition

### ISSUE THREAD

**Issue by guilfoos** [jekalmin/extended_openai_conversation#273]
I have Open WebUI running successfully in Docker, with an Ollama engine behind it. I can log in and use the LLM as expected.

However, when I try to connect via Home Assistant, I've had no end of problems. I've been able to iteratively improve things, but I've hit a roadblock: any input in the Assist pipeline returns "Unexpected error during intent recognition".

The Open WebUI logs seem OK:

> INFO  [open_webui.apps.openai.main] get_all_models()
> INFO  [open_webui.apps.ollama.main] get_all_models()
> INFO  [open_webui.apps.ollama.main] url: http://host.docker.internal:7869
> INFO:     x.x.x.x:49364 - "POST /api/chat/completions HTTP/1.1" 200 OK

The assist pipeline logs, however:

> Logger: homeassistant.components.assist_pipeline.pipeline
> Source: components/assist_pipeline/pipeline.py:1070
> integration: Assist pipeline (documentation, issues)
> First occurred: 9:50:36 AM (7 occurrences)
> Last logged: 10:09:22 AM
> 
> Unexpected error during intent recognition
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1070, in recognize_intent
>     conversation_result = await conversation.async_converse(
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ...<7 lines>...
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
>     result = await method(conversation_input)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 199, in async_process
>     query_response = await self.query(user_input, messages, exposed_entities, 0)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 376, in query
>     if response.usage.total_tokens > context_threshold:
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'total_tokens'

The only change I've made to the service setting is to change the model, everything else is default. The service itself is pointing at "http://docker-host:port/api", and is using the JWT token for the admin account in Open WebUI.

I've mucked around with other settings and have been able to get "method not allowed" errors, and model errors right in the assist output, but I'm kind of at my wits end.

**Comment by denisjoshua** [comment]
I follow cause I receive same error when I try to use the n8n backend. 
Thanks

**Comment by roshangautam** [comment]
@guilfoos I have this extension working with my local openwebui/ollama setup, so thought I would share. Hope it works for ya, good luck.
https://docs.openwebui.com/tutorials/integrations/continue-dev#add-or-update-apibase

**Comment by cl93a** [comment]
I think I tried every single possibility for the correct api domain for my open-webui instance ... can't get it to work :( Would really want to be able to talk to my own models of Open-Webui in Home Assistant. 
Tried it all:
/api
/api/v1
/ollama/v1
etc 

Visiting my instance /docs works perfect, I can do all api calls in that ui. But just can't get any url to work with extended_openai_conversation. Any other ideas for how to correctly fill in the extended_openai_conversation fields in Home Assistant for this to work?

**Comment by kiloptero** [comment]
in my case works randonmly.. some times

**Comment by Dantoes** [comment]
I get the same error for OpenRouter. When I installed `extended_openai_conversation` everything was working fine but a few days later it suddenly stopped working.

**Comment by guilfoos** [comment]
After setting this aside for a bit, I got my Ollama installation moved to kubernetes, but once again I get to this exact point. I've switched out the JWT token for an API key, but when connecting to https://hostname/api as the endpoint, I *consistently* get "AttributeError: 'NoneType' object has no attribute 'total_tokens'" from the assist pipeline. The only change I made from the default settings in extended_openui_conversation is to change the model to llama3, which is what I have installed and am testing with. This is an extremely frustrating issue.

Turning on debug logging, I can see the prompt (including exposed entities), and the response back from open webui. So the connectivity is good, but perhaps the default prompt is no good? Or the model? I've included the tail end of my prompt (after the exposed devices are 

> The current state of devices is provided in available devices.\nUse execute_services function only for requested action, not for current states.\nDo not execute service without user's confirmation.\nDo not restate or appreciate what user says, rather make a quick inquiry."}, {"role": "user", "content": "turn off the office lights"}]
> 2025-01-03 16:21:36.862 INFO (MainThread) [custom_components.extended_openai_conversation] Response {"id": "llama3:latest-de93b423-a1f2-476c-8cc2-c5f25a87e5c2", "choices": [{"finish_reason": "stop", "index": 0, "message": {"content": "*flip* The office lights are now turned off.", "role": "assistant"}}], "created": 1735939296, "model": "llama3:latest", "object": "chat.completion"}
> 2025-01-03 16:21:36.863 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1078, in recognize_intent
>     conversation_result = await conversation.async_converse(
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ...<7 lines>...
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
>     result = await method(conversation_input)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 199, in async_process
>     query_response = await self.query(user_input, messages, exposed_entities, 0)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/extended_openai_conversation/__init__.py", line 376, in query
>     if response.usage.total_tokens > context_threshold:
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'total_tokens'

@roshangautam - care to share your prompt? Model choice?

**Comment by guilfoos** [comment]
More reading: this seems to be a function problem. The logs don't indicate the function is being provided, and I've tried to use the "use tools" toggle to have the extension use tools as the function spec in the API has been deprecated. No change. Not sure how to improve my logging here to dig further.

**Comment by Fahmula** [comment]
@guilfoos 
You should use the /ollama/v1 endpoint. The error AttributeError: 'NoneType' object has no attribute 'total_tokens' occurs because the response does not contain the 'usage' dictionary or object. Here’s an example of a valid response:

`{
  "id": "chatcmpl-454",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "The kids' light is now set to 90%.",
        "role": "assistant"
      }
    }
  ],
  "created": 1736610718,
  "model": "krith/qwen2.5-14b-instruct:IQ4_XS",
  "object": "chat.completion",
  "system_fingerprint": "fp_ollama",
  "usage": {
    "completion_tokens": 13,
    "prompt_tokens": 503,
    "total_tokens": 516
  }
}`

I am having issues getting the integration to work with Open WebUI and Ollama. Based on my testing, it seems that all the local models I have tested do not support functions/tools. I was only able to get the krith/qwen2.5-14b-instruct:IQ4_XS model to work by modifying the `execute_service_single` function in the integration.

The integration expects the LLM to structure the function call when asking to turn on a light as follows:

`{
  "list": [
    {
      "domain": "light",
      "service": "turn_on",
      "service_data": {
        "entity_id": "light.living_room"
      }
    }
  ]
}`

However, the way all the local LLMs I have tested structure the function call is:

` "{"list":"[{'service': 'light.turn_off', 'entity_id': 'light.kids_light'}]"}"`

That's not a valid JSON and it's missing some required parameters such as `domain`  `service_data` and the `service` should only contains `turn_on`.

The models I have tested.

`llama3.1:8b`
`llama3.2:3b`
`qwen2.5:7b`
`qwen2.5:14b`
`mistral:7b`

**Comment by guilfoos** [comment]
Progress! Thank you, @Fahmula - I am now getting _something_ back from the LLM. Seems like there are a lot of gaps in documentation about how to do this. Endpoints, model selection. This is very much a "figure out how to bootstrap it yourself" ecosystem at the moment.

**Comment by Fahmula** [comment]
@guilfoos 

After a lot of testing I have flatten to default `execute_services` function which helps a lot of local models to reliability pass the needed arguments. I have also modify the default prompt by including areas and make the necessary changes to the integration ` execute_service` and `execute_service_single` functions.

I can push these changes to my fork of this integration if any one wants to test it but it might not be the best way to fix the issue even if it works.

**Comment by roshangautam** [comment]
> After setting this aside for a bit, I got my Ollama installation moved to kubernetes, but once again I get to this exact point. I've switched out the JWT token for an API key, but when connecting to https://hostname/api as the endpoint, I _consistently_ get "AttributeError: 'NoneType' object has no attribute 'total_tokens'" from the assist pipeline. The only change I made from the default settings in extended_openui_conversation is to change the model to llama3, which is what I have installed and am testing with. This is an extremely frustrating issue.
> 
> Turning on debug logging, I can see the prompt (including exposed entities), and the response back from open webui. So the connectivity is good, but perhaps the default prompt is no good? Or the model? I've included the tail end of my prompt (after the exposed devices are
> 
> > The current state of devices is provided in available devices.\nUse execute_services function only for requested action, not for current states.\nDo not execute service without user's confirmation.\nDo not restate or appreciate what user says, rather make a quick inquiry."}, {"role": "user", "content": "turn off the office lights"}]
> > 2025-01-03 16:21:36.862 INFO (MainThread) [custom_components.extended_openai_conversation] Response {"id": "llama3:latest-de93b423-a1f2-476c-8cc2-c5f25a87e5c2", "choices": [{"finish_reason": "stop", "index": 0, "message": {"content": "_flip_ The office lights are now turned off.", "role": "assistant"}}], "created": 1735939296, "model": "llama3:latest", "object": "chat.completion"}
> > 2025-01-03 16:21:36.863 ERROR (MainThread) [homeassistant.components.assist_pipeline.pipeline] Unexpected error during intent recognition
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1078, in recognize_intent
> > conversation_result = await conversation.async_converse(
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ...<7 lines>...
> > )
> > ^
> > File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
> > result = await method(conversation_input)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/extended_openai_conversation/**init**.py", line 199, in async_process
> > query_response = await self.query(user_input, messages, exposed_entities, 0)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/extended_openai_conversation/**init**.py", line 376, in query
> > if response.usage.total_tokens > context_threshold:
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > AttributeError: 'NoneType' object has no attribute 'total_tokens'
> 
> @roshangautam - care to share your prompt? Model choice?

I am using slightly modified versions of prompts provided by this repo. Nothing special. please check the examples folder: https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/prompt


Models am using:

- llama3.2:1b
- llama3.3:latest

both of these work really well with tool calling and control all devices with proper intent detection. I am using faster-whisper and piper for stt and tts respectively.

**Comment by guilfoos** [comment]
Given that I was able to resolve the issue, and I've documented it in the thread, I'm closing this. My issue now is that it's not doing what I want; the errors are no longer present.
