### ISSUE TITLE
You tried to access openai.Model, but this is no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by kamilk91** [jekalmin/extended_openai_conversation#69]
Hello,
Fresh installation yesterday, during "activating" my Voice Assistant in Settings => Integrations i have log:

```

2024-01-02 09:52:06.007 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Jass for extended_openai_conversation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 99, in async_setup_entry
    await validate_authentication(
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 154, in validate_authentication
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
openai.lib._old_api.APIRemovedInV1: 
You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 
Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

```

**Comment by jekalmin** [comment]
Probably duplicate issue (https://github.com/jekalmin/extended_openai_conversation/issues/62)
I will work on changes to `2024.1.x` core version soon!

**Comment by kamilk91** [comment]
@jekalmin it would be on new branch, or its (2024.1.x) version number ?

**Comment by jekalmin** [comment]
At first, I was going to release it in `1.0.0` version.
Now, I'm not certain whether I should keep using `0.0.x` format or use `2024.1.x` in version.

**Comment by jekalmin** [comment]
Can you try [1.0.0-beta1](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0-beta1)?

**Comment by kamilk91** [comment]
@jekalmin on my way to do that :)

**Comment by kamilk91** [comment]
Thanks a lot @jekalmin ! It works.

![image](https://github.com/jekalmin/extended_openai_conversation/assets/26136300/1ffd87c1-ff99-4148-85a6-922ef327d8b3)
