### ISSUE TITLE
Error in the extension in HA 2024.1

### ISSUE THREAD

**Issue by meni123** [jekalmin/extended_openai_conversation#75]
This is the error I am getting

```

Error setting up entry Asas for extended_openai_conversation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 99, in async_setup_entry
    await validate_authentication(
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 154, in validate_authentication
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: `https://github.com/openai/openai-python/discussions/742

```
Thanks

**Comment by saya6k** [comment]
You should update extended OpenAI conversation to 1.0.0b1

**Comment by jekalmin** [comment]
I just released [1.0.0](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0) version, which should be compatible with HA version `2024.1.x`
Please try this!

**Comment by GaWr26** [comment]
Thanks for this great integration! Unfortunately I get a Configuration Flow Error when adding the integration in 2024.1

**Comment by jekalmin** [comment]
Is there any error logs?

**Comment by meni123** [comment]
in version 1 Everything is fine, you can close the reference, thank you

**Comment by GaWr26** [comment]
> Is there any error logs?

I get this in the logs: 

Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 13:51:44 (8 occurrences)
Last logged: 16:41:41

Error occurred loading flow for integration extended_openai_conversation: cannot import name 'AsyncOpenAI' from 'openai' (/usr/local/lib/python3.11/site-packages/openai/__init__.py)

**Comment by jekalmin** [comment]
Can you try `0.0.11-beta1` or `0.0.10`?

**Comment by GaWr26** [comment]
Great Guess! It was actually a different intergration doing exactly that.

I removed It and now everything works and I love it! Thanks again for all the great work you put into this!

**Comment by jekalmin** [comment]
My pleasure :D
