### ISSUE TITLE
You tried to access openai.Model, but this is no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by droath** [jekalmin/extended_openai_conversation#79]
I recently updated to the latest version of HA [2024.1](https://www.home-assistant.io/blog/2024/01/03/release-20241/). It may not appear to be related, but it could be because the OpenAI version might have caused issues, resulting in breaking changes in your integration.  Here is the following error that was outputted in the log.

```
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/extended_openai_conversation/config_flow.py", line 130, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/extended_openai_conversation/config_flow.py", line 104, in validate_input
    await validate_authentication(
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 154, in validate_authentication
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

**Comment by ClaireRovic** [comment]
My integration errored with 'Failed to setup'. I will assume after the latest HA update.

**Comment by jekalmin** [comment]
Can you try [1.0.0](https://github.com/jekalmin/extended_openai_conversation/releases/tag/1.0.0) version?

If error persists, is there any integration that uses openai besides `openai_conversation` and `extended_openai_conversation`?
It can be caused by other integrations that uses openai.

**Comment by droath** [comment]
@jekalmin 

Thank you for the prompt fix. Version 1.0.0 has resolved this issue.
