### ISSUE TITLE
Todo List using wrong service

### ISSUE THREAD

**Issue by hagak** [jekalmin/extended_openai_conversation#98]
When you call "Add Milk to Shopping List"
 I get this error:
 This error originated from a custom integration.

Logger: custom_components.extended_openai_conversation
Source: custom_components/extended_openai_conversation/__init__.py:187
Integration: Extended OpenAI Conversation (documentation, issues)
First occurred: 4:10:49 PM (2 occurrences)
Last logged: 4:11:52 PM

Service todo.add_to_list not found.
Traceback (most recent call last):
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 187, in async_process
    response = await self.query(user_input, messages, exposed_entities, 0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 313, in query
    message = await self.execute_function_call(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/__init__.py", line 358, in execute_function
    result = await function_executor.execute(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 204, in execute
    return await self.execute_service(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/extended_openai_conversation/helpers.py", line 242, in execute_service
    raise ServiceNotFound(domain, service)
homeassistant.exceptions.ServiceNotFound: Service todo.add_to_list not found.

I think the issue is it is trying to call todo.add_to_list which does not exist in 2024.1, probably should be todo.add_item

**Comment by hagak** [comment]
not an issue closing

**Comment by jekalmin** [comment]
Thanks for reporting an issue.
The readme has been updated.
Please try this.

https://github.com/jekalmin/extended_openai_conversation/tree/main/examples/function#add_item_to_list
